# Important Modules

In [1]:
#importing Necessary modules

import pandas as pd

#importing deep learning modules

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM , Dense , Embedding
from sklearn.model_selection import train_test_split


# Dataset

Dataset consist of more than 10,000 collected data to make better model.Stored into .csv file

In [2]:
#Loading Dataset

dataset = pd.read_csv("dataset.csv");

In [3]:
#Glimpse of dataset

dataset.tail()

Eng  \
10251  Tom told Mary that he was going to kill himsel...   
10252  Tom's an irritating person to work with becaus...   
10253  I thought doing this would be easy, but we've ...   
10254  I thought that doing this would be easy, but w...   
10255  January, February, March, April, May, June, Ju...   

                                                    Beng  
10251  টম মেরিকে বললো যে ও নিজেকে হত্যা করতে চলেছিলো,...  
10252  টমের সঙ্গে কাজ করা খুব বিরক্তিকর কারণ ও কখনই ম...  
10253  আমি ভেবেছিলাম এটা করা সহজ হবে, কিন্তু আমরা সার...  
10254  আমি ভেবেছিলাম এটা করা সহজ হবে, কিন্তু আমরা সার...  
10255  বছরের বারোটা মাস হলো জানুয়ারি, ফেব্রুয়ারি, ম...

# Differenciating English And Bengali Words

 It's an approach of word preprocessing step of Natural Language Processing. 
         Here , tried to make speparate list for all english and bengali sentences for furthur process

In [4]:

#differenciation of english and bengali sentences

english_sentences = dataset["Eng"].tolist()

bengali_sentences = dataset["Beng"].tolist()

print(english_sentences)

['the', 'and', 'have', 'that', 'for', 'you', 'with', 'say', 'this', 'they', 'but', 'his', 'from', 'not', 'she', 'as', 'what', 'their', 'can', 'who', 'get', 'would', 'her', 'all', 'make', 'about', 'know', 'will', 'one', 'time', 'there', 'year', 'think', 'when', 'which', 'them', 'some', 'people', 'take', 'out', 'into', 'just', 'see', 'him', 'your', 'come', 'could', 'now', 'than', 'like', 'other', 'how', 'then', 'its', 'our', 'two', 'more', 'these', 'want', 'way', 'look', 'first', 'also', 'new', 'because', 'day', 'use', 'man', 'find', 'here', 'thing', 'give', 'many', 'well', 'only', 'those', 'tell', 'very', 'even', 'back', 'any', 'good', 'woman', 'through', 'life', 'child', 'work', 'down', 'may', 'after', 'should', 'call', 'world', 'over', 'school', 'still', 'try', 'last', 'ask', 'need', 'too', 'feel', 'three', 'state', 'never', 'become', 'between', 'high', 'really', 'something', 'most', 'another', 'much', 'family', 'own', 'leave', 'put', 'old', 'while', 'mean', 'keep', 'student', 'why', 

In [5]:
#English word Vectorization

token_vector_english = Tokenizer()

token_vector_english.fit_on_texts(english_sentences)

english_vec = token_vector_english.texts_to_sequences(english_sentences)


#Sample Vectorized List

print(english_vec)

[[6], [59], [20], [11], [37], [3], [41], [137], [19], [43], [105], [47], [70], [31], [40], [95], [15], [411], [25], [48], [51], [45], [131], [38], [278], [71], [33], [65], [91], [46], [36], [241], [64], [82], [299], [230], [138], [178], [99], [142], [504], [106], [67], [63], [23], [34], [102], [50], [123], [26], [266], [24], [684], [1233], [231], [190], [154], [255], [14], [242], [132], [174], [380], [243], [329], [118], [311], [542], [279], [27], [459], [244], [160], [139], [166], [267], [133], [56], [812], [62], [183], [101], [543], [1873], [460], [505], [78], [191], [94], [412], [167], [111], [544], [312], [351], [115], [213], [179], [134], [68], [184], [245], [107], [1874], [128], [1234], [1235], [685], [168], [151], [330], [352], [88], [972], [686], [86], [687], [112], [973], [256], [108], [545], [77], [203], [688], [689], [546], [1875], [547], [461], [413], [124], [87], [55], [246], [548], [247], [353], [549], [414], [506], [257], [600], [1876], [813], [974], [143], [415], [1877]

# Tokenization   And  Vectorization

In [6]:
#Bengali word Vectorization

token_vector_bengali = Tokenizer()

token_vector_bengali.fit_on_texts(bengali_sentences)

bengali_vec = token_vector_bengali.texts_to_sequences(bengali_sentences)

#Sample Vectorized List

print(bengali_vec)

[[2868], [153], [48], [19], [32], [6], [65], [608], [16], [132], [141], [55], [26], [11], [28], [997], [4], [186], [12, 2869], [2870], [404], [102], [55], [142], [7], [1288], [143], [2871], [118], [36], [405], [133], [23], [245], [58], [186], [30], [440], [368, 7], [1773], [119], [369], [150], [124], [21], [535], [205], [42], [693], [54], [1774], [206], [2872], [292], [49], [1289], [316], [1290], [43], [1291], [1775], [694], [2873], [317], [536], [269], [246], [440], [998], [25], [609], [158], [123], [17, 2874], [999], [2875], [608], [31], [821, 4], [318], [2876], [247], [1776], [2877], [822], [1000], [47], [695], [95, 205], [182], [270], [610], [1777], [2878], [1778], [271], [90, 370], [114], [101], [334], [31], [823, 7], [194], [824], [231], [62], [119], [1779], [164], [30], [2879], [183], [123], [1780], [1292], [195], [441], [2880], [224], [371], [441], [1293], [69], [269], [2881], [825], [319], [1001], [71], [23, 29], [1294], [82], [1781], [51], [2882], [537], [538], [71], [372], [

In [7]:
#Extracting Vocabulary

vocabulary_size_english = len(token_vector_english.word_index) + 1

vocabulary_size_bengali = len(token_vector_bengali.word_index) + 1

print(vocabulary_size_english)

5504


# Padding

In [8]:
#it's a python shortcut for taking maximum sentence

max_length = max(len(sentence) for sentence in (english_vec + bengali_vec))

print(max_length)

20


In [9]:
padded_english_vec = pad_sequences(english_vec, maxlen = max_length, padding = "post")

padded_bengali_vec = pad_sequences(bengali_vec, maxlen = max_length, padding = "post")

print(padded_bengali_vec)

[[2868    0    0 ...    0    0    0]
 [ 153    0    0 ...    0    0    0]
 [  48    0    0 ...    0    0    0]
 ...
 [   1  268    8 ...  786    0    0]
 [   1  268    8 ...  786    0    0]
 [ 437 6939 1003 ...    0    0    0]]


# Making Neural Network

In [10]:
embedding_dim = 256
units = 512

In [11]:
#Encoder
encoder_inputs = Input(shape=(max_length,))
encoder_emb = Embedding(input_dim=vocabulary_size_english,output_dim = embedding_dim)(encoder_inputs)
encoder_LSTM = LSTM(units , return_state = True)
encoder_outputs,state_h,state_c = encoder_LSTM(encoder_emb)
encoder_states = [state_h,state_c]

In [12]:
# Decoder

decoder_inputs = Input(shape=(max_length,))
dec_emb_layer = Embedding(input_dim=vocabulary_size_bengali, output_dim=embedding_dim)
dec_emb = dec_emb_layer(decoder_inputs)
decoder_lstm = LSTM(units, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(dec_emb, initial_state=encoder_states)
decoder_dense = Dense(vocabulary_size_bengali, activation='softmax')
output = decoder_dense(decoder_outputs)

# Deep Learning Model Creation

In [13]:
# Model
model = Model([encoder_inputs, decoder_inputs], output)

In [14]:
# Compilation of model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [15]:
X_train, X_val, y_train, y_val = train_test_split(padded_english_vec, padded_bengali_vec, test_size=0.2)

In [ ]:
model.fit([X_train, X_train], y_train, validation_data=([X_val, X_val], y_val), epochs=100, batch_size=64)

# time to get predicted output

In [16]:
def translate_sentence(sentence):
    seq = tokenizer_eng.texts_to_sequences([sentence])
    padded = pad_sequences(seq, maxlen=max_length, padding='post')
    translated = np.argmax(model.predict([padded, padded]), axis=-1)
    print(seq)
    
    translated_sentence = []
    for i in translated[0]:
        if i in tokenizer_beng.index_word:
            translated_sentence.append(tokenizer_beng.index_word[i])
        else:
            translated_sentence.append(' ')  
        
    return ' '.join(translated_sentence)

In [ ]:
input_sentence = input('Enter your sentence:')
translated_sentence = translate_sentence(input_sentence)
print(f"Translated: {translated_sentence}")